apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "entitle-agent.fullname" . }}
  labels:
    app: {{ include "entitle-agent.fullname" . }}
    environment: {{ .Values.global.environment }}
    tags.datadoghq.com/env: {{ .Values.global.environment }}
    tags.datadoghq.com/service: {{ include "entitle-agent.fullname" . }}-{{ .Values.global.environment }}
    tags.datadoghq.com/version: {{ include "entitle-agent.imageTag" .}}
    {{- include "entitle-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      app: {{ include "entitle-agent.fullname" . }}
      {{- include "entitle-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/docker-login: {{ include (print $.Template.BasePath "/docker-login.yaml") . | sha256sum }}
        ad.datadoghq.com/{{ include "entitle-agent.fullname" . }}.logs: '[{"source": "{{ include "entitle-agent.fullname" . }}"}]'
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "entitle-agent.fullname" . }}
        environment: {{ .Values.global.environment }}
        tags.datadoghq.com/env: {{ .Values.global.environment }}
        tags.datadoghq.com/service: {{ include "entitle-agent.fullname" . }}-{{ .Values.global.environment }}
        tags.datadoghq.com/version: {{ include "entitle-agent.imageTag" .}}
        {{- include "entitle-agent.selectorLabels" . | nindent 8 }}
        {{- if eq .Values.platform.mode "azure" }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      containers:
      - env:
        {{- if eq .Values.agent.mode "websocket" }}
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "entitle-agent.fullname" . }}-secret
              key: TOKEN
        - name: KMS_TYPE
          value: {{ include "entitle-agent.kmsType" . }}
        {{- else }}
        - name: ENTITLE_WEBSOCKET_ENABLED
          value: "false"
        - name: ENTITLE_KMS_TYPE
          value: {{ include "entitle-agent.kmsType" . }}
        {{- if .Values.agent.kafka.bootstrapServers }}
        - name: ENTITLE_KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.agent.kafka.bootstrapServers }}
        {{- end }}
        - name: ENTITLE_JSON_CONFIGURATION
          valueFrom:
            secretKeyRef:
              name: {{ include "entitle-agent.fullname" . }}-secret
              key: ENTITLE_JSON_CONFIGURATION
              optional: false
        {{- end }}
        {{- if eq .Values.platform.mode "azure" }}
        - name: AZURE_KEY_VAULT_NAME
          value: {{ .Values.platform.azure.keyVaultName }}
        {{- end }}
        image: {{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: {{ include "entitle-agent.fullname" . }}
        {{- with .Values.agent.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        startupProbe:
          exec:
            command:
              - python
              - scripts/healthcheck.py
          initialDelaySeconds: 5
          timeoutSeconds: 30
      imagePullSecrets:
        - name: {{ include "entitle-agent.fullname" . }}-docker-login
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "entitle-agent.serviceAccountName" .}}
