{{- if eq .Values.kmsType "hashicorp_vault" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "entitle-agent.fullname" . }}-hashicorp-vault-secret
  labels:
  {{- include "entitle-agent.labels" . | nindent 4 }}
stringData:
  HASHICORP_VAULT_CONNECTION_STRING: {{ .Values.externalKmsParams.hashicorpVaultConnectionString }}
{{- end }}
